[versions]
# App Version
versionCode = "1"
versionName = "1.0.0"

compileSdk = "36"
minSdk = "29"
targetSdk = "36"

# Gradle Plugin
android-gradle-plugin = "8.11.2"

# Kotlin
kotlin-core = "2.2.21"
kotlin-ktlint-gradle = "14.0.1"

# Kotlinx
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
kotlinx-serialization = "1.9.0"
kotlinx-collections-immutable = "0.4.0"

# Compose & UI
compose-multiplatform = "1.9.3"
androidx-core = "1.17.0"
androidx-datastore = "1.2.0"
androidx-lifecycle-runtime = "2.10.0"
androidx-startup = "1.2.0"
androidx-activity-compose = "1.12.1"
jetbrains-androidx-navigation = "2.9.1"

# Room Database
androidx-room = "2.8.4"
androidx-sqlite = "2.6.2"

# DI
koin = "4.1.1"

# Network
ktor = "3.3.3"
ktorfit = "2.7.1"

# BuildKonfig
build-konfig = "0.17.1"

# Image
coil = "3.3.0"

# Util
napier = "2.7.1"
ksp = "2.2.21-2.0.4"

# Test
junit5 = "6.0.1"
junit4 = "4.13.2"
junit-android = "1.3.0"
kotest = "6.0.7"
mockk = "1.14.7"
espressoCore = "3.7.0"
kotlinStdlib = "2.2.21"
kotlinTest = "2.2.21"
runner = "1.7.0"
core = "1.7.0"

[libraries]

# Gradle Plugin
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle-plugin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin-core" }
room-gradle-plugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "androidx-room" }
compose-compiler-gradle-plugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin-core" }
compose-gradle-plugin = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "compose-multiplatform" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
kotlinx-serialization-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin-core" }

# Kotlinx
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines"}
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }

# Androidx
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidx-core" }
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "androidx-datastore" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidx-datastore" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidx-startup" }

# Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle-runtime" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle-runtime" }
androidx-navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "jetbrains-androidx-navigation" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test"}

# Ktor
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktorfit = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" }
ktorfit-ksp = { module = "de.jensklingenberg.ktorfit:ktorfit-ksp", version.ref = "ktorfit" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

# Room Database
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-sqlite-bundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "androidx-sqlite" }

# DI
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version.ref = "koin" }
koin-compose-viewmodel-navigation = { group = "io.insert-koin", name = "koin-compose-viewmodel-navigation", version.ref = "koin" }

# Network
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }

# Image
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-ktor = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }

# Util
napier = { group = "io.github.aakira", name = "napier", version.ref = "napier" }

# Test
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit5" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api"}
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine"}
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params"}
junit-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine"}
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher"}
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
junit = { group = "junit", name = "junit", version.ref = "junit4" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-android" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
kotest-framework = { group = "io.kotest", name = "kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-assertion = { group = "io.kotest", name = "kotest-assertions-core-jvm", version.ref = "kotest" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlinTest" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
core = { group = "androidx.test", name = "core", version.ref = "core" }

[plugins]
# Kotlin
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-core" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-core" }
kotlin-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "kotlin-ktlint-gradle" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-core" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin-core" }

# Compose
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-core" }

# Android
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }

# AndroidX
androidx-room = { id = "androidx.room", version.ref = "androidx-room" }

# Util
ksp-gradle-plugin = { id = "com.google.devtools.ksp", version.ref = "ksp" }

# Buildkonfig
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "build-konfig" }

# Test
android-test = { id = "com.android.test", version.ref = "android-gradle-plugin" }

[bundles]
plugins = [
    "android-gradle-plugin",
    "kotlin-gradle-plugin",
    "room-gradle-plugin",
    "compose-compiler-gradle-plugin",
    "compose-gradle-plugin",
    "ksp-gradle-plugin",
    "kotlinx-serialization-gradle-plugin",
]
