# https://github.com/naver/simple-labeler
# token: Required GitHub에서 제공하는 토큰
# labels: Required 이벤트 발생 시 추가할 Label 목록. 콤마(,)로 구분
# duplicate: 기존에 붙은 Label 중 이 패턴과 일치하는 것이 있다면 새 Label을 추가하지 않습니다. (glob 패턴 사용)

name: Simple Labeler
on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
  simple-labeler:
    runs-on: [ubuntu-latest]
    steps:
      - name: Label to PR
        uses: naver/simple-labeler@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: "D-3"
          duplicate: "D-*"
